[package]
name = "rain-tofu-erc20-decimals"
version = "0.1.2"

[profile.default]
src = 'src'
out = 'out'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
evm_version = "cancun"

# optimizer settings for debugging
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# optimizer settings for snapshotting.
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

# Build metadata used for testing rain meta aware contracts in this folder rather
# than expose ffi to forge.
fs_permissions = []
libs = ["dependencies"]

[dependencies]
forge-std = "1.16.1"
"rain-deploy" = "0.1.3"
"rain-extrospection" = "0.1.1"
"rain-solmem" = "0.1.3"

[soldeer]
recursive_deps = false

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
flare = "${FLARE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
arbitrum = { key = "${CI_DEPLOY_ARBITRUM_ETHERSCAN_API_KEY}" }
base = { key = "${CI_DEPLOY_BASE_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${CI_DEPLOY_BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
flare = { key = "${CI_DEPLOY_FLARE_ETHERSCAN_API_KEY}" }
polygon = { key = "${CI_DEPLOY_POLYGON_ETHERSCAN_API_KEY}" }
